### ISSUE TITLE
发送文本信息失败: AssertionError [ERR_ASSERTION]: 1204 == 0

### ISSUE THREAD

**Issue by acheong08** [fuergaosi233/wechat-chatgpt#116]
```
AssertionError [ERR_ASSERTION]: 1204 == 0
    at Object.equal (/home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/node_modules/wechat4u/src/util/global.js:53:14)
    at /home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/node_modules/wechat4u/src/core.js:477:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async PuppetWechat4u.messageSendText (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/node_modules/wechaty-puppet-wechat4u/src/puppet-wechat4u.ts:765:5)
    at async WechatifiedUserClass.say (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/node_modules/wechaty/src/user-modules/contact.ts:338:19)
    at async ChatGPTBot.trySay (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/src/chatgpt.ts:198:7)
    at async ChatGPTBot.onPrivateMessage (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/src/chatgpt.ts:243:5)
    at async ChatGPTBot.onMessage (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/src/chatgpt.ts:270:16)
    at async WechatyImpl.<anonymous> (file:///home/acheong/Projects/experiments/GPT/wechat/wechat-chatgpt/src/main.ts:30:7) {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 1204,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '发送文本信息失败'
}
```

**Comment by fuergaosi233** [comment]
Can you make sure your WeChat account is real name authenticated🤔?

**Comment by acheong08** [comment]
How do I do that?

**Comment by acheong08** [comment]
I just checked. It is real name authenticated

**Comment by fuergaosi233** [comment]
Try login via https://web.wechat.com/？

**Comment by acheong08** [comment]
Doesn't work with new accounts created after 2020 I think:
```
For the security of your account, you cannot log in to Weixin for Web. You can go to https://weixin.qq.com/ to download the Weixin app and log in.
```

**Comment by kylesean** [comment]
```
11:31:49 WARN PuppetWechat4u monkeyPatch() wechat4u.checkPolling() notifyMobile() exception: AssertionError [ERR_ASSERTION]: 1101 == 0
uncaughtException AssertionError [ERR_ASSERTION]: 1101 == 0
    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)
    at /app/node_modules/wechat4u/src/core.js:228:16
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 1101 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/src/util/global.js:53:14)\n' +
    '    at /app/node_modules/wechat4u/src/core.js:228:16\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}
```
same error as his. real name account

**Comment by Cat-Overflow** [comment]
I guess you didn't judge msg.self() or message type which caused the say method to send the wrong object.  
I also encountered the same problem, and solved it by adding a msg.self() judgment.
The code is as follows:
```
async function onMessage(msg){
    if (msg.type() !== wechaty.Message.Type.Text)
        return
    if (msg.self())
        return
    console.log('receive msg',msg.toString())
    const room = msg.room()
    if (room){
        return
    }else{
        const response = 'hello'
        await msg.say(response)
    }
    console.log('solved msg',msg.toString())
}
```

**Comment by acheong08** [comment]
Is it not possible to send send a message to yourself?

**Comment by Cat-Overflow** [comment]
> Is it not possible to send send a message to yourself?
I'm not sure. I believe it is not possible to send a message to yourself by default.
When you click on the message box or send a message, a corresponding msg will appear. If you do not check msg.self(), you may send a message to yourself, which could cause an error. Therefore, you need to discard the corresponding message when msg.self() is true and not process the msg.
If you have a need to send a message to yourself, i think you should modify the corresponding file according to the issue#200. However, I am not sure if there are other issues because I do not want to send a message to myself.
The above is my opinion, and I don't know if there is anything wrong.

**Comment by Cat-Overflow** [comment]
> Is it not possible to send send a message to yourself?

I'm not sure. I believe it is not possible to send a message to yourself by default.
When you click on the message box or send a message to yourself, a corresponding msg will appear. If you do not check msg.self(), you may send a message to yourself, which could cause an error. Therefore, you need to discard the corresponding message when msg.self() is true and not process the msg.
If you have a need to send a message to yourself, you should modify the corresponding file according to the issue#200. However, I am not sure if there are other issues because I do not want to send a message to myself.
The above is my opinion, and I don't know if there is anything wrong.

**Comment by acheong08** [comment]
I think you can do it normally. The issue with this seems to be that new accounts or accounts created by non Chinese ID holders can't use the Web interface (which is the puppeteer used in this case)
